name: build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    with:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    runs-on: ubuntu-20.04
    steps:
      - uses: "actions/checkout@v2"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: build msv
        uses: docker/build-push-action@v2
        with:
          context: .
          file: msv.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/msv:v0.1
          build-args: |
            JOBS=2
            GIT_USER=${{ secrets.GH_USER }}
            GIT_TOKEN=${{ input.GH_TOKEN }}
